version: '3.8'

services:
  pocket-poktroll-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    networks:
      - default

  # Extending from server's docker-compose.yml for backend services
  redis:
    extends:
      file: ./server/docker-compose.yml
      service: redis
    networks:
      - default

  pocket-poktroll-explorer-backend:
    extends:
      file: ./server/docker-compose.yml
      service: api
    networks:
      - default

networks:
  default:


volumes:
  redis-data: 