name: Deploy Explorer

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: '--no-warnings'

jobs:
  garnix:
    name: Wait on Garnix CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait on Garnix CI Check Suite
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          REF: ${{ github.head_ref }}
        run: |
          sleep 15
          
          status=''
          
          while [[ $status != 'completed' ]]; do
            check_suites=$(gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/repos/$REPO/commits/$REF/check-suites")
              
            status=$(echo "$check_suites" | jq -r '.check_suites | .[] | select(.app.name == "Garnix CI") | .status')
            sleep 15
          done

          conclusion=$(echo "$check_suites" | jq -r '.check_suites | .[] | select(.app.name == "Garnix CI") | .conclusion')

          case "$conclusion" in
            failure | timed_out | action_required | stale | startup_failure)
              echo "ERROR: Garnix CI concluded with $conclusion"
              exit 1
              ;;
            *)
              echo "INFO: Garnix CI concluded with $conclusion"
              ;;
          esac

  deploy-preview:
    runs-on: ['ubuntu-latest']
    needs: [garnix]
    permissions:
      contents: read
      pull-requests: write
    env:
      npm_config_yes: true
    environment: 'app-preview'
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: nixbuild/nix-quick-install-action@v28
      - name: Fetch from Cache
        run: |
          nix develop
          nix build .#explorer
      - name: '[preview] ðŸ”¶ Publish to Cloudflare Pages'
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
        run: npx --yes wrangler@latest pages --project-name="app" deploy result >> /tmp/app_deploy.txt
      - name: Set Deploy Output
        run: |
          {
            echo 'DEPLOY_OUTPUT<<EOF'
            tail -n 2 /tmp/app_deploy.txt
            echo 'EOF'
          } >> $GITHUB_ENV
      - name: Comment Site Deploy Results
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # App ðŸ¤Œ
            ${{ env.DEPLOY_OUTPUT }}

            **${{ env.LAST_UPDATED_AT }}**
          comment_tag: deploy-app-preview-result

  deploy-production:
    runs-on: 'ubuntu-latest'
    needs: [garnix]
    env:
      npm_config_yes: true
    environment: 'explorer-production'
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: nixbuild/nix-quick-install-action@v28
      - name: Fetch from Cache
        run: |
          nix develop
          nix build .#explorer
      - name: '[production] ðŸ”¶ Publish to Cloudflare Pages'
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
        run: npx --yes wrangler@latest pages --project-name="explorer" --branch="main" deploy result
