
name: Deploy to ping.pub

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  deploy:
    name: Ping deploy
    runs-on: mainnet 
    steps:
    - name: print
      run: echo ${GITHUB_REF#refs/heads/}
    - name: Git Checkout Latest
      uses: actions/checkout@v3
      
    - name: Install
      run: yarn install

    - name: Build
      run: yarn run vue-cli-service build

    - name: Deploy
      run: cp -rf ./dist/* /var/www/html/